# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 18:40
from __future__ import unicode_literals

import apps.mypeckyspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypeckyspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/peccy.png', upload_to=apps.mypeckyspace.models.user_directory_path),
        ),
    ]
