# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 18:42
from __future__ import unicode_literals

import apps.mypeckyspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypeckyspace', '0002_auto_20180417_1140'),
    ]

    operations = [
       
    ]
