# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 21:31
from __future__ import unicode_literals

import apps.mypeckyspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypeckyspace', '0003_auto_20180417_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='static/media/documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to=apps.mypeckyspace.models.user_directory_path),
        ),
    ]
