# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 21:31
from __future__ import unicode_literals

import apps.mypeckyspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypeckyspace', '0003_auto_20180417_1142'),
    ]

    operations = [
     
    ]
