# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypeckyspace', '0004_auto_20180417_1431'),
    ]

    operations = [
      
    ]
