# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypeckyspace', '0007_auto_20180418_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uploaded_file',
            new_name='upload',
        ),
    ]
